SET FOREIGN_KEY_CHECKS=0/0xd
REPLACE INTO `patientflags_tag_role` VALUES
(1,'Adherence'),
(1,'Anonymous'),
(1,'Application: Administers System'),
(1,'Application: Configures Appointment Scheduling'),
(1,'Application: Configures Forms'),
(1,'Application: Configures Metadata'),
(1,'Application: Edits Existing Encounters'),
(1,'Application: Enters ADT Events'),
(1,'Application: Enters Vitals'),
(1,'Application: Has Super User Privileges'),
(1,'Application: Manages Atlas'),
(1,'Application: Manages Provider Schedules'),
(1,'Application: Records Allergies'),
(1,'Application: Registers Patients'),
(1,'Application: Requests Appointments'),
(1,'Application: Schedules And Overbooks Appointments'),
(1,'Application: Schedules Appointments'),
(1,'Application: Sees Appointment Schedule'),
(1,'Application: Uses Capture Vitals App'),
(1,'Application: Uses Patient Summary'),
(1,'Application: Writes Clinical Notes'),
(1,'Authenticated'),
(1,'Careandsupport'),
(1,'Clinician'),
(1,'Dataclerk'),
(1,'Lab'),
(1,'Organizational: Doctor'),
(1,'Organizational: Hospital Administrator'),
(1,'Organizational: Nurse'),
(1,'Organizational: Registration Clerk'),
(1,'Organizational: System Administrator'),
(1,'Pharmacist'),
(1,'Privilege Level: Full'),
(1,'Privilege Level: High'),
(1,'Provider')/0xd
SET FOREIGN_KEY_CHECKS=1/0xd