REPLACE INTO `role_role` VALUES
  ('Privilege Level: Full','Adherence'),
  ('Provider','Adherence'),
  ('Organizational: Registration Clerk','ANC'),
  ('Privilege Level: Full','ANC'),
  ('Provider','ANC'),
  ('ANC','Application: Enters Vitals'),
  ('Clinician','cdc_user_role'),
  ('Lab','cdc_user_role'),
  ('Application: Enters Vitals','Clinician'),
  ('Application: Records Allergies','Clinician'),
  ('Application: Schedules And Overbooks Appointments','Clinician'),
  ('Application: Sees Appointment Schedule','Clinician'),
  ('Application: Uses Patient Summary','Clinician'),
  ('Application: Writes Clinical Notes','Clinician'),
  ('Organizational: Doctor','Clinician'),
  ('Privilege Level: Full','Clinician'),
  ('Provider','Clinician'),
  ('Provider','Nurse'),
  ('Privilege Level: Full','Nurse'),
  ('Application: Enters Vitals','Nurse'),
  ('Application: Records Allergies','Nurse'),
  ('Application: Schedules And Overbooks Appointments','Nurse'),
  ('Application: Sees Appointment Schedule','Nurse'),
  ('Application: Uses Patient Summary','Nurse'),
  ('Application: Writes Clinical Notes','Nurse'),
  ('Organizational: Registration Clerk','HTS'),
  ('Privilege Level: Full','HTS'),
  ('Provider','HTS'),
  ('Application: Enters ADT Events','Lab'),
  ('Provider','Lab'),
  ('Privilege Level: Full','MandE'),
  ('MandE','Application: Schedules Appointments'),
  ('Provider','MandE'),
  ('Privilege Level: Full','Pharmacist'),
  ('Pharmacist','Application: Schedules Appointments'),
  ('Provider','Pharmacist')/0xd