SET FOREIGN_KEY_CHECKS=0/0xd
REPLACE INTO `role_privilege` VALUES
('Adherence','App: coreapps.findPatient'),
  ('Adherence','App: coreapps.patientDashboard'),
  ('Adherence','App: coreapps.patientVisits'),
  ('Adherence','App: coreapps.summaryDashboard'),
  ('Adherence','App: patientqueueing.providerDashboard'),
  ('Adherence','Task: coreapps.createVisit'),
  ('Adherence','Task: coreapps.deletePatientProgram'),
  ('Adherence','Task: coreapps.editPatientProgram'),
  ('Adherence','Task: coreapps.endVisit'),
  ('Adherence','Task: coreapps.enrollInProgram'),
  ('Adherence','Task: coreapps.mergeVisits'),
  ('Adherence','Task: emr.patient.encounter.edit'),
  ('Adherence','Task: patientqueueing.completePatientQueue'),
  ('Adherence','Task: patientqueueing.sendPatientToQueue'),  
('Adherence','Task: appointmentschedulingui.overbookAppointments'),
('Adherence','Task: appointmentschedulingui.bookAppointments'),
('Adherence','Task: appointmentschedulingui.viewConfidential'),
('Adherence','App: appointmentschedulingui.home'),
('Adherence','App: appointmentschedulingui.viewAppointments'),
('Adherence','Manage Appointment Types'),
('Adherence','Schedule Appointments'),
('Adherence','App: coreapps.activeVisits'),
  ('ANC','App: coreapps.activeVisits'),
  ('ANC','App: coreapps.findPatient'),
  ('ANC','App: coreapps.patientDashboard'),
  ('ANC','App: coreapps.patientVisits'),
  ('ANC','App: coreapps.summaryDashboard'),
  ('ANC','App: patientqueueing.providerDashboard'),
  ('ANC','Task: coreapps.createVisit'),
  ('ANC','Task: coreapps.deletePatientProgram'),
  ('ANC','Task: coreapps.editPatientProgram'),
  ('ANC','Task: coreapps.endVisit'),
  ('ANC','Task: coreapps.enrollInProgram'),
  ('ANC','Task: coreapps.mergeVisits'),
  ('ANC','Task: emr.patient.encounter.edit'),
  ('ANC','Task: patientqueueing.completePatientQueue'),
  ('ANC','Task: patientqueueing.sendPatientToQueue'),
  ('Application: Administers System','App: coreapps.systemAdministration'),
  ('Application: Administers System','App: referenceapplication.legacyAdmin'),
  ('Application: Configures Appointment Scheduling','App: appointmentschedulingui.appointmentTypes'),
  ('Application: Configures Appointment Scheduling','App: appointmentschedulingui.home'),
  ('Application: Configures Forms','App: coreapps.configuremetadata'),
  ('Application: Configures Forms','App: formentryapp.forms'),
  ('Application: Configures Metadata','App: coreapps.configuremetadata'),
  ('Application: Edits Existing Encounters','Task: emr.patient.encounter.delete'),
  ('Application: Edits Existing Encounters','Task: emr.patient.encounter.edit'),
  ('Application: Enters ADT Events','App: coreapps.activeVisits'),
  ('Application: Enters ADT Events','App: coreapps.findPatient'),
  ('Application: Enters ADT Events','Task: coreapps.createRetrospectiveVisit'),
  ('Application: Enters ADT Events','Task: coreapps.createVisit'),
  ('Application: Enters ADT Events','Task: coreapps.endVisit'),
  ('Application: Enters ADT Events','Task: coreapps.mergeVisits'),
  ('Application: Enters ADT Events','Task: referenceapplication.simpleAdmission'),
  ('Application: Enters ADT Events','Task: referenceapplication.simpleDischarge'),
  ('Application: Enters ADT Events','Task: referenceapplication.simpleTransfer'),
  ('Application: Enters Vitals','App: coreapps.activeVisits'),
  ('Application: Enters Vitals','App: coreapps.findPatient'),
  ('Application: Enters Vitals','Task: referenceapplication.vitals'),
  ('Application: Manages Atlas','App: atlas.manage'),
  ('Application: Manages Atlas','App: coreapps.systemAdministration'),
  ('Application: Manages Provider Schedules','App: appointmentschedulingui.home'),
  ('Application: Manages Provider Schedules','App: appointmentschedulingui.providerSchedules'),
  ('Application: Records Allergies','Task: Modify Allergies'),
  ('Application: Registers Patients','App: coreapps.activeVisits'),
  ('Application: Registers Patients','App: coreapps.patientDashboard'),
  ('Application: Registers Patients','App: registrationapp.registerPatient'),
  ('Application: Requests Appointments','Task: appointmentschedulingui.requestAppointments'),
  ('Application: Schedules And Overbooks Appointments','Task: appointmentschedulingui.overbookAppointments'),
  ('Application: Schedules Appointments','Task: appointmentschedulingui.bookAppointments'),
  ('Application: Schedules Appointments','Task: appointmentschedulingui.viewConfidential'),
  ('Application: Sees Appointment Schedule','App: appointmentschedulingui.home'),
  ('Application: Sees Appointment Schedule','App: appointmentschedulingui.viewAppointments'),
  ('Application: Uses Capture Vitals App','App: referenceapplication.vitals'),
  ('Application: Uses Patient Summary','App: coreapps.findPatient'),
  ('Application: Uses Patient Summary','App: coreapps.patientDashboard'),
  ('Application: Uses Patient Summary','App: coreapps.patientVisits'),
  ('Application: Writes Clinical Notes','App: coreapps.activeVisits'),
  ('Application: Writes Clinical Notes','App: coreapps.findPatient'),
  ('Application: Writes Clinical Notes','Task: referenceapplication.simpleVisitNote'),
  ('Authenticated','Get Concept Classes'),
  ('Authenticated','Get Concept Datatypes'),
  ('Authenticated','Get Encounter Types'),
  ('Authenticated','Get Field Types'),
  ('Authenticated','Get Global Properties'),
  ('Authenticated','Get Identifier Types'),
  ('Authenticated','Get Locations'),
  ('Authenticated','Get Order Types'),
  ('Authenticated','Get Person Attribute Types'),
  ('Authenticated','Get Privileges'),
  ('Authenticated','Get Relationship Types'),
  ('Authenticated','Get Relationships'),
  ('Authenticated','Get Roles'),
  ('Authenticated','Patient Overview - View Relationships'),
  ('Authenticated','View Concept Classes'),
  ('Authenticated','View Concept Datatypes'),
  ('Authenticated','View Encounter Types'),
  ('Authenticated','View Field Types'),
  ('Authenticated','View Global Properties'),
  ('Authenticated','View Identifier Types'),
  ('Authenticated','View Locations'),
  ('Authenticated','View Order Types'),
  ('Authenticated','View Person Attribute Types'),
  ('Authenticated','View Privileges'),
  ('Authenticated','View Relationship Types'),
  ('Authenticated','View Relationships'),
  ('Authenticated','View Roles'),
  ('cdc_user_role','App: Access Cashier Tasks'),
  ('cdc_user_role','App: Access Inventory Tasks'),
  ('cdc_user_role','App: View Cashier App'),
  ('cdc_user_role','App: View Inventory App'),
  ('cdc_user_role','Task: Access Create Operation'),
  ('cdc_user_role','Task: Access Inventory Reports'),
  ('cdc_user_role','Task: Access Inventory Task'),
  ('cdc_user_role','Task: Access Stock Take'),
  ('cdc_user_role','Task: Adjust Cashier Bills'),
  ('cdc_user_role','Task: Cashier Timesheets'),
  ('cdc_user_role','Task: coreapps.editPatientProgram'),
  ('cdc_user_role','Task: coreapps.enrollInProgram'),
  ('cdc_user_role','Task: Create new bill'),
  ('cdc_user_role','Task: emr.patient.encounter.edit'),
  ('cdc_user_role','Task: Manage Cashier Metadata'),
  ('cdc_user_role','Task: Manage Cashier Module'),
  ('cdc_user_role','Task: Manage Condition Lists'),
  ('cdc_user_role','Task: Manage Inventory Metadata'),
  ('cdc_user_role','Task: Manage Inventory Module'),
  ('cdc_user_role','Task: View Cashier Reports'),
  ('cdc_user_role','Task: View Stock Operations'),
  ('Clinician','App: patientqueueing.providerDashboard'),
  ('Clinician','Task: coreapps.deletePatientProgram'),
  ('Clinician','Task: coreapps.editPatientProgram'),
  ('Clinician','Task: coreapps.enrollInProgram'),
  ('Clinician','Task: emr.patient.encounter.edit'),
  ('Clinician','Task: patientqueueing.completePatientQueue'),
  ('Clinician','Task: patientqueueing.sendPatientToQueue'),  
  ('Clinician','App: registrationapp.registerPatient'),
  ('Nurse','App: patientqueueing.providerDashboard'),
  ('Nurse','Task: coreapps.deletePatientProgram'),
  ('Nurse','Task: coreapps.editPatientProgram'),
  ('Nurse','Task: coreapps.enrollInProgram'),
  ('Nurse','Task: emr.patient.encounter.edit'),
  ('Nurse','Task: patientqueueing.completePatientQueue'),
  ('Nurse','Task: patientqueueing.sendPatientToQueue'),  
  ('HTS','App: coreapps.findPatient'),
  ('HTS','App: coreapps.patientVisits'),
  ('HTS','App: coreapps.summaryDashboard'),
  ('HTS','App: formentryapp.forms'),
  ('HTS','App: patientqueueing.providerDashboard'),
  ('HTS','Task: coreapps.createVisit'),
  ('HTS','Task: coreapps.deletePatientProgram'),
  ('HTS','Task: coreapps.editPatientProgram'),
  ('HTS','Task: coreapps.endVisit'),
  ('HTS','Task: coreapps.enrollInProgram'),
  ('HTS','Task: coreapps.mergeVisits'),
  ('HTS','Task: emr.patient.encounter.edit'),
  ('HTS','Task: patientqueueing.completePatientQueue'),
  ('HTS','Task: patientqueueing.sendPatientToQueue'),
  ('Lab','App: coreapps.patientDashboard'),
  ('Lab','App: coreapps.patientVisits'),
  ('Lab','App: coreapps.summaryDashboard'),
  ('Lab','App: patientqueueing.providerDashboard'),
  ('Lab','Task: coreapps.deletePatientProgram'),
  ('Lab','Task: coreapps.editPatientProgram'),
  ('Lab','Task: coreapps.enrollInProgram'),
  ('Lab','Task: patientqueueing.completePatientQueue'),
  ('Lab','Task: patientqueueing.sendPatientToQueue'),
  ('MandE','App: coreapps.activeVisits'),
  ('MandE','App: registrationapp.registerPatient'),
  ('MandE','App: reportingui.reports'),
  ('MandE','App: coreapps.findPatient'),
  ('MandE','App: coreapps.patientDashboard'),
  ('MandE','App: coreapps.patientVisits'),
  ('MandE','App: coreapps.summaryDashboard'),
  ('MandE','App: patientqueueing.providerDashboard'),
  ('MandE','Task: coreapps.createVisit'),
  ('MandE','Task: coreapps.deletePatientProgram'),
  ('MandE','Task: coreapps.editPatientProgram'),
  ('MandE','Task: coreapps.endVisit'),
  ('MandE','Task: coreapps.enrollInProgram'),
  ('MandE','Task: coreapps.mergeVisits'),
  ('MandE','Task: emr.patient.encounter.edit'),
  ('MandE','Task: patientqueueing.completePatientQueue'),
  ('MandE','Task: patientqueueing.sendPatientToQueue'),
  ('MandE','Nigeriaemr Privilege'),
  ('Pharmacist','App: coreapps.findPatient'),
  ('Pharmacist','App: coreapps.activeVisits'),
  ('Pharmacist','App: reportingui.reports'),
  ('Pharmacist','App: coreapps.mergePatient'),
  ('Pharmacist','App: coreapps.patientDashboard'),
  ('Pharmacist','App: coreapps.patientVisits'),
  ('Pharmacist','App: coreapps.summaryDashboard'),
  ('Pharmacist','App: patientqueueing.providerDashboard'),
  ('Pharmacist','Task: coreapps.deletePatientProgram'),
  ('Pharmacist','Task: coreapps.editPatientProgram'),
  ('Pharmacist','Task: coreapps.endVisit'),
  ('Pharmacist','Task: coreapps.enrollInProgram'),
  ('Pharmacist','Task: coreapps.mergeVisits'),
  ('Pharmacist','Task: patientqueueing.completePatientQueue'),
  ('Pharmacist','Task: patientqueueing.sendPatientToQueue'),
  ('Privilege Level: Full','Add Allergies'),
  ('Privilege Level: Full','Add Cohorts'),
  ('Privilege Level: Full','Add Concept Proposals'),
  ('Privilege Level: Full','Add Encounters'),
  ('Privilege Level: Full','Add HL7 Inbound Archive'),
  ('Privilege Level: Full','Add HL7 Inbound Exception'),
  ('Privilege Level: Full','Add HL7 Inbound Queue'),
  ('Privilege Level: Full','Add HL7 Source'),
  ('Privilege Level: Full','Add Observations'),
  ('Privilege Level: Full','Add Orders'),
  ('Privilege Level: Full','Add Patient Identifiers'),
  ('Privilege Level: Full','Add Patient Programs'),
  ('Privilege Level: Full','Add Patients'),
  ('Privilege Level: Full','Add People'),
  ('Privilege Level: Full','Add Problems'),
  ('Privilege Level: Full','Add Relationships'),
  ('Privilege Level: Full','Add Report Objects'),
  ('Privilege Level: Full','Add Reports'),
  ('Privilege Level: Full','Add Users'),
  ('Privilege Level: Full','Add Visits'),
  ('Privilege Level: Full','Adjust Cashier Bills'),
  ('Privilege Level: Full','Assign System Developer Role'),
  ('Privilege Level: Full','Configure Visits'),
  ('Privilege Level: Full','Delete Cohorts'),
  ('Privilege Level: Full','Delete Concept Proposals'),
  ('Privilege Level: Full','Delete Encounters'),
  ('Privilege Level: Full','Delete HL7 Inbound Archive'),
  ('Privilege Level: Full','Delete HL7 Inbound Exception'),
  ('Privilege Level: Full','Delete HL7 Inbound Queue'),
  ('Privilege Level: Full','Delete Notes'),
  ('Privilege Level: Full','Delete Observations'),
  ('Privilege Level: Full','Delete Orders'),
  ('Privilege Level: Full','Delete Patient Identifiers'),
  ('Privilege Level: Full','Delete Patient Programs'),
  ('Privilege Level: Full','Delete Patients'),
  ('Privilege Level: Full','Delete People'),
  ('Privilege Level: Full','Delete Relationships'),
  ('Privilege Level: Full','Delete Report Objects'),
  ('Privilege Level: Full','Delete Reports'),
  ('Privilege Level: Full','Delete Users'),
  ('Privilege Level: Full','Delete Visits'),
  ('Privilege Level: Full','Edit Allergies'),
  ('Privilege Level: Full','Edit Cohorts'),
  ('Privilege Level: Full','Edit Concept Proposals'),
  ('Privilege Level: Full','Edit conditions'),
  ('Privilege Level: Full','Edit Encounters'),
  ('Privilege Level: Full','Edit Notes'),
  ('Privilege Level: Full','Edit Observations'),
  ('Privilege Level: Full','Edit Orders'),
  ('Privilege Level: Full','Edit Patient Identifiers'),
  ('Privilege Level: Full','Edit Patient Programs'),
  ('Privilege Level: Full','Edit Patients'),
  ('Privilege Level: Full','Edit People'),
  ('Privilege Level: Full','Edit Problems'),
  ('Privilege Level: Full','Edit Relationships'),
  ('Privilege Level: Full','Edit Report Objects'),
  ('Privilege Level: Full','Edit Reports'),
  ('Privilege Level: Full','Edit User Passwords'),
  ('Privilege Level: Full','Edit Users'),
  ('Privilege Level: Full','Edit Visits'),
  ('Privilege Level: Full','Form Entry'),
  ('Privilege Level: Full','Generate Batch of Identifiers'),
  ('Privilege Level: Full','Get Allergies'),
  ('Privilege Level: Full','Get Care Settings'),
  ('Privilege Level: Full','Get Concept Attribute Types'),
  ('Privilege Level: Full','Get Concept Classes'),
  ('Privilege Level: Full','Get Concept Datatypes'),
  ('Privilege Level: Full','Get Concept Map Types'),
  ('Privilege Level: Full','Get Concept Proposals'),
  ('Privilege Level: Full','Get Concept Reference Terms'),
  ('Privilege Level: Full','Get Concept Sources'),
  ('Privilege Level: Full','Get Concepts'),
  ('Privilege Level: Full','Get conditions'),
  ('Privilege Level: Full','Get Database Changes'),
  ('Privilege Level: Full','Get Encounter Roles'),
  ('Privilege Level: Full','Get Encounter Types'),
  ('Privilege Level: Full','Get Encounters'),
  ('Privilege Level: Full','Get Field Types'),
  ('Privilege Level: Full','Get Forms'),
  ('Privilege Level: Full','Get Global Properties'),
  ('Privilege Level: Full','Get HL7 Inbound Archive'),
  ('Privilege Level: Full','Get HL7 Inbound Exception'),
  ('Privilege Level: Full','Get HL7 Inbound Queue'),
  ('Privilege Level: Full','Get HL7 Source'),
  ('Privilege Level: Full','Get Identifier Types'),
  ('Privilege Level: Full','Get Location Attribute Types'),
  ('Privilege Level: Full','Get Locations'),
  ('Privilege Level: Full','Get Notes'),
  ('Privilege Level: Full','Get Observations'),
  ('Privilege Level: Full','Get Order Frequencies'),
  ('Privilege Level: Full','Get Order Sets'),
  ('Privilege Level: Full','Get Order Types'),
  ('Privilege Level: Full','Get Orders'),
  ('Privilege Level: Full','Get Patient Cohorts'),
  ('Privilege Level: Full','Get Patient Identifiers'),
  ('Privilege Level: Full','Get Patient Programs'),
  ('Privilege Level: Full','Get Patients'),
  ('Privilege Level: Full','Get People'),
  ('Privilege Level: Full','Get Person Attribute Types'),
  ('Privilege Level: Full','Get Privileges'),
  ('Privilege Level: Full','Get Problems'),
  ('Privilege Level: Full','Get Programs'),
  ('Privilege Level: Full','Get Providers'),
  ('Privilege Level: Full','Get Relationship Types'),
  ('Privilege Level: Full','Get Relationships'),
  ('Privilege Level: Full','Get Roles'),
  ('Privilege Level: Full','Get Users'),
  ('Privilege Level: Full','Get Visit Attribute Types'),
  ('Privilege Level: Full','Get Visit Types'),
  ('Privilege Level: Full','Get Visits'),
  ('Privilege Level: Full','Manage Address Hierarchy'),
  ('Privilege Level: Full','Manage Address Templates'),
  ('Privilege Level: Full','Manage Alerts'),
  ('Privilege Level: Full','Manage Appointment Types'),
  ('Privilege Level: Full','Manage Appointments Settings'),
  ('Privilege Level: Full','Manage Atlas Data'),
  ('Privilege Level: Full','Manage Auto Generation Options'),
  ('Privilege Level: Full','Manage Cashier Bills'),
  ('Privilege Level: Full','Manage Cashier Metadata'),
  ('Privilege Level: Full','Manage Cashier Timesheets'),
  ('Privilege Level: Full','Manage Cohort Definitions'),
  ('Privilege Level: Full','Manage Concept Attribute Types'),
  ('Privilege Level: Full','Manage Concept Classes'),
  ('Privilege Level: Full','Manage Concept Datatypes'),
  ('Privilege Level: Full','Manage Concept Map Types'),
  ('Privilege Level: Full','Manage Concept Name tags'),
  ('Privilege Level: Full','Manage Concept Reference Terms'),
  ('Privilege Level: Full','Manage Concept Sources'),
  ('Privilege Level: Full','Manage Concept Stop Words'),
  ('Privilege Level: Full','Manage Concepts'),
  ('Privilege Level: Full','Manage Data Set Definitions'),
  ('Privilege Level: Full','Manage Dimension Definitions'),
  ('Privilege Level: Full','Manage Encounter Roles'),
  ('Privilege Level: Full','Manage Encounter Types'),
  ('Privilege Level: Full','Manage Field Types'),
  ('Privilege Level: Full','Manage Flags'),
  ('Privilege Level: Full','Manage FormEntry XSN'),
  ('Privilege Level: Full','Manage Forms'),
  ('Privilege Level: Full','Manage Global Properties'),
  ('Privilege Level: Full','Manage HL7 Messages'),
  ('Privilege Level: Full','Manage Identifier Sources'),
  ('Privilege Level: Full','Manage Identifier Types'),
  ('Privilege Level: Full','Manage Implementation Id'),
  ('Privilege Level: Full','Manage Indicator Definitions'),
  ('Privilege Level: Full','Manage Inventory Items'),
  ('Privilege Level: Full','Manage Inventory Metadata'),
  ('Privilege Level: Full','Manage Inventory Operations'),
  ('Privilege Level: Full','Manage Inventory Stockrooms'),
  ('Privilege Level: Full','Manage Jasper Reports'),
  ('Privilege Level: Full','Manage Location Attribute Types'),
  ('Privilege Level: Full','Manage Location Tags'),
  ('Privilege Level: Full','Manage Locations'),
  ('Privilege Level: Full','Manage Metadata Mapping'),
  ('Privilege Level: Full','Manage Modules'),
  ('Privilege Level: Full','Manage Order Frequencies'),
  ('Privilege Level: Full','Manage Order Sets'),
  ('Privilege Level: Full','Manage Order Types'),
  ('Privilege Level: Full','Manage OWA'),
  ('Privilege Level: Full','Manage Person Attribute Types'),
  ('Privilege Level: Full','Manage Privileges'),
  ('Privilege Level: Full','Manage Programs'),
  ('Privilege Level: Full','Manage Provider Schedules'),
  ('Privilege Level: Full','Manage Providers'),
  ('Privilege Level: Full','Manage Relationship Types'),
  ('Privilege Level: Full','Manage Relationships'),
  ('Privilege Level: Full','Manage Report Definitions'),
  ('Privilege Level: Full','Manage Report Designs'),
  ('Privilege Level: Full','Manage Reports'),
  ('Privilege Level: Full','Manage RESTWS'),
  ('Privilege Level: Full','Manage Roles'),
  ('Privilege Level: Full','Manage Rule Definitions'),
  ('Privilege Level: Full','Manage Scheduled Report Tasks'),
  ('Privilege Level: Full','Manage Scheduler'),
  ('Privilege Level: Full','Manage Search Index'),
  ('Privilege Level: Full','Manage synonym group'),
  ('Privilege Level: Full','Manage Synonym Groups'),
  ('Privilege Level: Full','Manage Token Registrations'),
  ('Privilege Level: Full','Manage Tokens'),
  ('Privilege Level: Full','Manage Visit Attribute Types'),
  ('Privilege Level: Full','Manage Visit Types'),
  ('Privilege Level: Full','Patient Dashboard - View Chart Search Section'),
  ('Privilege Level: Full','Patient Dashboard - View Demographics Section'),
  ('Privilege Level: Full','Patient Dashboard - View Encounters Section'),
  ('Privilege Level: Full','Patient Dashboard - View Forms Section'),
  ('Privilege Level: Full','Patient Dashboard - View Graphs Section'),
  ('Privilege Level: Full','Patient Dashboard - View Overview Section'),
  ('Privilege Level: Full','Patient Dashboard - View Patient Summary'),
  ('Privilege Level: Full','Patient Dashboard - View Regimen Section'),
  ('Privilege Level: Full','Patient Dashboard - View Visits Section'),
  ('Privilege Level: Full','Patient Overview - View Allergies'),
  ('Privilege Level: Full','Patient Overview - View Patient Actions'),
  ('Privilege Level: Full','Patient Overview - View Patient Flags'),
  ('Privilege Level: Full','Patient Overview - View Problem List'),
  ('Privilege Level: Full','Patient Overview - View Programs'),
  ('Privilege Level: Full','Patient Overview - View Relationships'),
  ('Privilege Level: Full','Provider Management - Admin'),
  ('Privilege Level: Full','Provider Management API'),
  ('Privilege Level: Full','Provider Management API - Read-only'),
  ('Privilege Level: Full','Provider Management Dashboard - Edit Patients'),
  ('Privilege Level: Full','Provider Management Dashboard - Edit Providers'),
  ('Privilege Level: Full','Provider Management Dashboard - View Historical'),
  ('Privilege Level: Full','Provider Management Dashboard - View Patients'),
  ('Privilege Level: Full','Provider Management Dashboard - View Providers'),
  ('Privilege Level: Full','Purge Cashier Bills'),
  ('Privilege Level: Full','Purge Cashier Metadata'),
  ('Privilege Level: Full','Purge Cashier Timesheets'),
  ('Privilege Level: Full','Purge Field Types'),
  ('Privilege Level: Full','Purge Inventory Items'),
  ('Privilege Level: Full','Purge Inventory Metadata'),
  ('Privilege Level: Full','Purge Inventory Operations'),
  ('Privilege Level: Full','Purge Inventory Stockrooms'),
  ('Privilege Level: Full','Refund Money'),
  ('Privilege Level: Full','Remove Allergies'),
  ('Privilege Level: Full','Remove Problems'),
  ('Privilege Level: Full','Reprint Receipt'),
  ('Privilege Level: Full','Request Appointments'),
  ('Privilege Level: Full','Rollback Inventory Operations'),
  ('Privilege Level: Full','Run Chart Search commands'),
  ('Privilege Level: Full','Run Reports'),
  ('Privilege Level: Full','Schedule Appointments'),
  ('Privilege Level: Full','Share Metadata'),
  ('Privilege Level: Full','Squeezing Appointments'),
  ('Privilege Level: Full','Test Flags'),
  ('Privilege Level: Full','Update Appointment Status'),
  ('Privilege Level: Full','Update HL7 Inbound Archive'),
  ('Privilege Level: Full','Update HL7 Inbound Exception'),
  ('Privilege Level: Full','Update HL7 Inbound Queue'),
  ('Privilege Level: Full','Update HL7 Source'),
  ('Privilege Level: Full','Upload Batch of Identifiers'),
  ('Privilege Level: Full','Upload XSN'),
  ('Privilege Level: Full','View Administration Functions'),
  ('Privilege Level: Full','View Allergies'),
  ('Privilege Level: Full','View Appointment Types'),
  ('Privilege Level: Full','View Appointments'),
  ('Privilege Level: Full','View Appointments Blocks'),
  ('Privilege Level: Full','View Appointments Statistics'),
  ('Privilege Level: Full','View Calculations'),
  ('Privilege Level: Full','View Cashier Bills'),
  ('Privilege Level: Full','View Cashier Metadata'),
  ('Privilege Level: Full','View Cashier Timesheets'),
  ('Privilege Level: Full','View Concept Classes'),
  ('Privilege Level: Full','View Concept Datatypes'),
  ('Privilege Level: Full','View Concept Map Types'),
  ('Privilege Level: Full','View Concept Proposals'),
  ('Privilege Level: Full','View Concept Reference Terms'),
  ('Privilege Level: Full','View Concept Sources'),
  ('Privilege Level: Full','View Concepts'),
  ('Privilege Level: Full','View Data Entry Statistics'),
  ('Privilege Level: Full','View Database Changes'),
  ('Privilege Level: Full','View Encounter Roles'),
  ('Privilege Level: Full','View Encounter Types'),
  ('Privilege Level: Full','View Encounters'),
  ('Privilege Level: Full','View Field Types'),
  ('Privilege Level: Full','View Forms'),
  ('Privilege Level: Full','View Global Properties'),
  ('Privilege Level: Full','View HL7 Inbound Archive'),
  ('Privilege Level: Full','View HL7 Inbound Exception'),
  ('Privilege Level: Full','View HL7 Inbound Queue'),
  ('Privilege Level: Full','View HL7 Source'),
  ('Privilege Level: Full','View Identifier Types'),
  ('Privilege Level: Full','View Inventory Items'),
  ('Privilege Level: Full','View Inventory Metadata'),
  ('Privilege Level: Full','View Inventory Operations'),
  ('Privilege Level: Full','View Inventory Stockrooms'),
  ('Privilege Level: Full','View Jasper Reports'),
  ('Privilege Level: Full','View Location Attribute Types'),
  ('Privilege Level: Full','View Locations'),
  ('Privilege Level: Full','View Metadata Via Mapping'),
  ('Privilege Level: Full','View Navigation Menu'),
  ('Privilege Level: Full','View Observations'),
  ('Privilege Level: Full','View Order Types'),
  ('Privilege Level: Full','View Orders'),
  ('Privilege Level: Full','View Patient Appointment History'),
  ('Privilege Level: Full','View Patient Cohorts'),
  ('Privilege Level: Full','View Patient Identifiers'),
  ('Privilege Level: Full','View Patient Programs'),
  ('Privilege Level: Full','View Patients'),
  ('Privilege Level: Full','View People'),
  ('Privilege Level: Full','View Person Attribute Types'),
  ('Privilege Level: Full','View Privileges'),
  ('Privilege Level: Full','View Problems'),
  ('Privilege Level: Full','View Programs'),
  ('Privilege Level: Full','View Provider Schedules'),
  ('Privilege Level: Full','View Providers'),
  ('Privilege Level: Full','View Relationship Types'),
  ('Privilege Level: Full','View Relationships'),
  ('Privilege Level: Full','View Report Objects'),
  ('Privilege Level: Full','View Reports'),
  ('Privilege Level: Full','View RESTWS'),
  ('Privilege Level: Full','View Roles'),
  ('Privilege Level: Full','View Rule Definitions'),
  ('Privilege Level: Full','View Token Registrations'),
  ('Privilege Level: Full','View Unpublished Forms'),
  ('Privilege Level: Full','View Users'),
  ('Privilege Level: Full','View Visit Attribute Types'),
  ('Privilege Level: Full','View Visit Types'),
  ('Privilege Level: Full','View Visits'),
  ('Privilege Level: High','Add Allergies'),
  ('Privilege Level: High','Add Cohorts'),
  ('Privilege Level: High','Add Concept Proposals'),
  ('Privilege Level: High','Add Encounters'),
  ('Privilege Level: High','Add HL7 Inbound Archive'),
  ('Privilege Level: High','Add HL7 Inbound Exception'),
  ('Privilege Level: High','Add HL7 Inbound Queue'),
  ('Privilege Level: High','Add HL7 Source'),
  ('Privilege Level: High','Add Observations'),
  ('Privilege Level: High','Add Orders'),
  ('Privilege Level: High','Add Patient Identifiers'),
  ('Privilege Level: High','Add Patient Programs'),
  ('Privilege Level: High','Add Patients'),
  ('Privilege Level: High','Add People'),
  ('Privilege Level: High','Add Problems'),
  ('Privilege Level: High','Add Relationships'),
  ('Privilege Level: High','Add Users'),
  ('Privilege Level: High','Add Visits'),
  ('Privilege Level: High','Adjust Cashier Bills'),
  ('Privilege Level: High','Assign System Developer Role'),
  ('Privilege Level: High','Configure Visits'),
  ('Privilege Level: High','Delete Cohorts'),
  ('Privilege Level: High','Delete Concept Proposals'),
  ('Privilege Level: High','Delete Encounters'),
  ('Privilege Level: High','Delete HL7 Inbound Archive'),
  ('Privilege Level: High','Delete HL7 Inbound Exception'),
  ('Privilege Level: High','Delete HL7 Inbound Queue'),
  ('Privilege Level: High','Delete Notes'),
  ('Privilege Level: High','Delete Observations'),
  ('Privilege Level: High','Delete Orders'),
  ('Privilege Level: High','Delete Patient Identifiers'),
  ('Privilege Level: High','Delete Patient Programs'),
  ('Privilege Level: High','Delete Patients'),
  ('Privilege Level: High','Delete People'),
  ('Privilege Level: High','Delete Relationships'),
  ('Privilege Level: High','Delete Report Objects'),
  ('Privilege Level: High','Delete Reports'),
  ('Privilege Level: High','Delete Users'),
  ('Privilege Level: High','Delete Visits'),
  ('Privilege Level: High','Edit Allergies'),
  ('Privilege Level: High','Edit Cohorts'),
  ('Privilege Level: High','Edit Concept Proposals'),
  ('Privilege Level: High','Edit conditions'),
  ('Privilege Level: High','Edit Encounters'),
  ('Privilege Level: High','Edit Notes'),
  ('Privilege Level: High','Edit Observations'),
  ('Privilege Level: High','Edit Orders'),
  ('Privilege Level: High','Edit Patient Identifiers'),
  ('Privilege Level: High','Edit Patient Programs'),
  ('Privilege Level: High','Edit Patients'),
  ('Privilege Level: High','Edit People'),
  ('Privilege Level: High','Edit Problems'),
  ('Privilege Level: High','Edit Relationships'),
  ('Privilege Level: High','Edit User Passwords'),
  ('Privilege Level: High','Edit Users'),
  ('Privilege Level: High','Edit Visits'),
  ('Privilege Level: High','Form Entry'),
  ('Privilege Level: High','Generate Batch of Identifiers'),
  ('Privilege Level: High','Get Allergies'),
  ('Privilege Level: High','Get Care Settings'),
  ('Privilege Level: High','Get Concept Attribute Types'),
  ('Privilege Level: High','Get Concept Classes'),
  ('Privilege Level: High','Get Concept Datatypes'),
  ('Privilege Level: High','Get Concept Map Types'),
  ('Privilege Level: High','Get Concept Proposals'),
  ('Privilege Level: High','Get Concept Reference Terms'),
  ('Privilege Level: High','Get Concept Sources'),
  ('Privilege Level: High','Get Concepts'),
  ('Privilege Level: High','Get conditions'),
  ('Privilege Level: High','Get Database Changes'),
  ('Privilege Level: High','Get Encounter Roles'),
  ('Privilege Level: High','Get Encounter Types'),
  ('Privilege Level: High','Get Encounters'),
  ('Privilege Level: High','Get Field Types'),
  ('Privilege Level: High','Get Forms'),
  ('Privilege Level: High','Get Global Properties'),
  ('Privilege Level: High','Get HL7 Inbound Archive'),
  ('Privilege Level: High','Get HL7 Inbound Exception'),
  ('Privilege Level: High','Get HL7 Inbound Queue'),
  ('Privilege Level: High','Get HL7 Source'),
  ('Privilege Level: High','Get Identifier Types'),
  ('Privilege Level: High','Get Location Attribute Types'),
  ('Privilege Level: High','Get Locations'),
  ('Privilege Level: High','Get Notes'),
  ('Privilege Level: High','Get Observations'),
  ('Privilege Level: High','Get Order Frequencies'),
  ('Privilege Level: High','Get Order Sets'),
  ('Privilege Level: High','Get Order Types'),
  ('Privilege Level: High','Get Orders'),
  ('Privilege Level: High','Get Patient Cohorts'),
  ('Privilege Level: High','Get Patient Identifiers'),
  ('Privilege Level: High','Get Patient Programs'),
  ('Privilege Level: High','Get Patients'),
  ('Privilege Level: High','Get People'),
  ('Privilege Level: High','Get Person Attribute Types'),
  ('Privilege Level: High','Get Privileges'),
  ('Privilege Level: High','Get Problems'),
  ('Privilege Level: High','Get Programs'),
  ('Privilege Level: High','Get Providers'),
  ('Privilege Level: High','Get Relationship Types'),
  ('Privilege Level: High','Get Relationships'),
  ('Privilege Level: High','Get Roles'),
  ('Privilege Level: High','Get Users'),
  ('Privilege Level: High','Get Visit Attribute Types'),
  ('Privilege Level: High','Get Visit Types'),
  ('Privilege Level: High','Get Visits'),
  ('Privilege Level: High','Manage Address Hierarchy'),
  ('Privilege Level: High','Manage Address Templates'),
  ('Privilege Level: High','Manage Alerts'),
  ('Privilege Level: High','Manage Appointment Types'),
  ('Privilege Level: High','Manage Appointments Settings'),
  ('Privilege Level: High','Manage Atlas Data'),
  ('Privilege Level: High','Manage Auto Generation Options'),
  ('Privilege Level: High','Manage Cashier Bills'),
  ('Privilege Level: High','Manage Cashier Metadata'),
  ('Privilege Level: High','Manage Cashier Timesheets'),
  ('Privilege Level: High','Manage Cohort Definitions'),
  ('Privilege Level: High','Manage Concept Attribute Types'),
  ('Privilege Level: High','Manage Concept Classes'),
  ('Privilege Level: High','Manage Concept Datatypes'),
  ('Privilege Level: High','Manage Concept Map Types'),
  ('Privilege Level: High','Manage Concept Name tags'),
  ('Privilege Level: High','Manage Concept Reference Terms'),
  ('Privilege Level: High','Manage Concept Sources'),
  ('Privilege Level: High','Manage Concept Stop Words'),
  ('Privilege Level: High','Manage Concepts'),
  ('Privilege Level: High','Manage Data Set Definitions'),
  ('Privilege Level: High','Manage Dimension Definitions'),
  ('Privilege Level: High','Manage Encounter Roles'),
  ('Privilege Level: High','Manage Encounter Types'),
  ('Privilege Level: High','Manage Field Types'),
  ('Privilege Level: High','Manage Flags'),
  ('Privilege Level: High','Manage FormEntry XSN'),
  ('Privilege Level: High','Manage Forms'),
  ('Privilege Level: High','Manage Global Properties'),
  ('Privilege Level: High','Manage HL7 Messages'),
  ('Privilege Level: High','Manage Identifier Sources'),
  ('Privilege Level: High','Manage Identifier Types'),
  ('Privilege Level: High','Manage Implementation Id'),
  ('Privilege Level: High','Manage Indicator Definitions'),
  ('Privilege Level: High','Manage Inventory Items'),
  ('Privilege Level: High','Manage Inventory Metadata'),
  ('Privilege Level: High','Manage Inventory Operations'),
  ('Privilege Level: High','Manage Inventory Stockrooms'),
  ('Privilege Level: High','Manage Jasper Reports'),
  ('Privilege Level: High','Manage Location Attribute Types'),
  ('Privilege Level: High','Manage Location Tags'),
  ('Privilege Level: High','Manage Locations'),
  ('Privilege Level: High','Manage Metadata Mapping'),
  ('Privilege Level: High','Manage Modules'),
  ('Privilege Level: High','Manage Order Frequencies'),
  ('Privilege Level: High','Manage Order Sets'),
  ('Privilege Level: High','Manage Order Types'),
  ('Privilege Level: High','Manage OWA'),
  ('Privilege Level: High','Manage Person Attribute Types'),
  ('Privilege Level: High','Manage Programs'),
  ('Privilege Level: High','Manage Provider Schedules'),
  ('Privilege Level: High','Manage Providers'),
  ('Privilege Level: High','Manage Relationship Types'),
  ('Privilege Level: High','Manage Relationships'),
  ('Privilege Level: High','Manage Report Definitions'),
  ('Privilege Level: High','Manage Report Designs'),
  ('Privilege Level: High','Manage Reports'),
  ('Privilege Level: High','Manage RESTWS'),
  ('Privilege Level: High','Manage Roles'),
  ('Privilege Level: High','Manage Rule Definitions'),
  ('Privilege Level: High','Manage Scheduled Report Tasks'),
  ('Privilege Level: High','Manage Scheduler'),
  ('Privilege Level: High','Manage Search Index'),
  ('Privilege Level: High','Manage synonym group'),
  ('Privilege Level: High','Manage Synonym Groups'),
  ('Privilege Level: High','Manage Token Registrations'),
  ('Privilege Level: High','Manage Tokens'),
  ('Privilege Level: High','Manage Visit Attribute Types'),
  ('Privilege Level: High','Manage Visit Types'),
  ('Privilege Level: High','Patient Dashboard - View Chart Search Section'),
  ('Privilege Level: High','Patient Dashboard - View Demographics Section'),
  ('Privilege Level: High','Patient Dashboard - View Encounters Section'),
  ('Privilege Level: High','Patient Dashboard - View Forms Section'),
  ('Privilege Level: High','Patient Dashboard - View Graphs Section'),
  ('Privilege Level: High','Patient Dashboard - View Overview Section'),
  ('Privilege Level: High','Patient Dashboard - View Patient Summary'),
  ('Privilege Level: High','Patient Dashboard - View Regimen Section'),
  ('Privilege Level: High','Patient Dashboard - View Visits Section'),
  ('Privilege Level: High','Patient Overview - View Allergies'),
  ('Privilege Level: High','Patient Overview - View Patient Actions'),
  ('Privilege Level: High','Patient Overview - View Patient Flags'),
  ('Privilege Level: High','Patient Overview - View Problem List'),
  ('Privilege Level: High','Patient Overview - View Programs'),
  ('Privilege Level: High','Patient Overview - View Relationships'),
  ('Privilege Level: High','Provider Management - Admin'),
  ('Privilege Level: High','Provider Management API'),
  ('Privilege Level: High','Provider Management API - Read-only'),
  ('Privilege Level: High','Provider Management Dashboard - Edit Patients'),
  ('Privilege Level: High','Provider Management Dashboard - Edit Providers'),
  ('Privilege Level: High','Provider Management Dashboard - View Historical'),
  ('Privilege Level: High','Provider Management Dashboard - View Patients'),
  ('Privilege Level: High','Provider Management Dashboard - View Providers'),
  ('Privilege Level: High','Purge Cashier Bills'),
  ('Privilege Level: High','Purge Cashier Metadata'),
  ('Privilege Level: High','Purge Cashier Timesheets'),
  ('Privilege Level: High','Purge Field Types'),
  ('Privilege Level: High','Purge Inventory Items'),
  ('Privilege Level: High','Purge Inventory Metadata'),
  ('Privilege Level: High','Purge Inventory Operations'),
  ('Privilege Level: High','Purge Inventory Stockrooms'),
  ('Privilege Level: High','Refund Money'),
  ('Privilege Level: High','Remove Allergies'),
  ('Privilege Level: High','Remove Problems'),
  ('Privilege Level: High','Reprint Receipt'),
  ('Privilege Level: High','Request Appointments'),
  ('Privilege Level: High','Rollback Inventory Operations'),
  ('Privilege Level: High','Run Chart Search commands'),
  ('Privilege Level: High','Run Reports'),
  ('Privilege Level: High','Schedule Appointments'),
  ('Privilege Level: High','Squeezing Appointments'),
  ('Privilege Level: High','Test Flags'),
  ('Privilege Level: High','Update Appointment Status'),
  ('Privilege Level: High','Update HL7 Inbound Archive'),
  ('Privilege Level: High','Update HL7 Inbound Exception'),
  ('Privilege Level: High','Update HL7 Inbound Queue'),
  ('Privilege Level: High','Update HL7 Source'),
  ('Privilege Level: High','Upload Batch of Identifiers'),
  ('Privilege Level: High','Upload XSN'),
  ('Privilege Level: High','View Administration Functions'),
  ('Privilege Level: High','View Allergies'),
  ('Privilege Level: High','View Appointment Types'),
  ('Privilege Level: High','View Appointments'),
  ('Privilege Level: High','View Appointments Blocks'),
  ('Privilege Level: High','View Appointments Statistics'),
  ('Privilege Level: High','View Calculations'),
  ('Privilege Level: High','View Cashier Bills'),
  ('Privilege Level: High','View Cashier Metadata'),
  ('Privilege Level: High','View Cashier Timesheets'),
  ('Privilege Level: High','View Concept Classes'),
  ('Privilege Level: High','View Concept Datatypes'),
  ('Privilege Level: High','View Concept Map Types'),
  ('Privilege Level: High','View Concept Proposals'),
  ('Privilege Level: High','View Concept Reference Terms'),
  ('Privilege Level: High','View Concept Sources'),
  ('Privilege Level: High','View Concepts'),
  ('Privilege Level: High','View Data Entry Statistics'),
  ('Privilege Level: High','View Database Changes'),
  ('Privilege Level: High','View Encounter Roles'),
  ('Privilege Level: High','View Encounter Types'),
  ('Privilege Level: High','View Encounters'),
  ('Privilege Level: High','View Field Types'),
  ('Privilege Level: High','View Forms'),
  ('Privilege Level: High','View Global Properties'),
  ('Privilege Level: High','View HL7 Inbound Archive'),
  ('Privilege Level: High','View HL7 Inbound Exception'),
  ('Privilege Level: High','View HL7 Inbound Queue'),
  ('Privilege Level: High','View HL7 Source'),
  ('Privilege Level: High','View Identifier Types'),
  ('Privilege Level: High','View Inventory Items'),
  ('Privilege Level: High','View Inventory Metadata'),
  ('Privilege Level: High','View Inventory Operations'),
  ('Privilege Level: High','View Inventory Stockrooms'),
  ('Privilege Level: High','View Jasper Reports'),
  ('Privilege Level: High','View Location Attribute Types'),
  ('Privilege Level: High','View Locations'),
  ('Privilege Level: High','View Metadata Via Mapping'),
  ('Privilege Level: High','View Navigation Menu'),
  ('Privilege Level: High','View Observations'),
  ('Privilege Level: High','View Order Types'),
  ('Privilege Level: High','View Orders'),
  ('Privilege Level: High','View Patient Appointment History'),
  ('Privilege Level: High','View Patient Cohorts'),
  ('Privilege Level: High','View Patient Identifiers'),
  ('Privilege Level: High','View Patient Programs'),
  ('Privilege Level: High','View Patients'),
  ('Privilege Level: High','View People'),
  ('Privilege Level: High','View Person Attribute Types'),
  ('Privilege Level: High','View Privileges'),
  ('Privilege Level: High','View Problems'),
  ('Privilege Level: High','View Programs'),
  ('Privilege Level: High','View Provider Schedules'),
  ('Privilege Level: High','View Providers'),
  ('Privilege Level: High','View Relationship Types'),
  ('Privilege Level: High','View Relationships'),
  ('Privilege Level: High','View Report Objects'),
  ('Privilege Level: High','View Reports'),
  ('Privilege Level: High','View RESTWS'),
  ('Privilege Level: High','View Roles'),
  ('Privilege Level: High','View Rule Definitions'),
  ('Privilege Level: High','View Token Registrations'),
  ('Privilege Level: High','View Unpublished Forms'),
  ('Privilege Level: High','View Users'),
  ('Privilege Level: High','View Visit Attribute Types'),
  ('Privilege Level: High','View Visit Types'),
  ('Privilege Level: High','View Visits')/0xd
  SET FOREIGN_KEY_CHECKS=1/0xd