REPLACE INTO `role_role` VALUES
  ('Privilege Level: Full','Adherence'),
  ('Provider','Adherence'),
  ('Organizational: Registration Clerk','ANC'),
  ('Privilege Level: Full','ANC'),
  ('Provider','ANC'),
  ('ANC','Application: Enters Vitals'),
  ('ANC','Application: Uses Capture Vitals App'),
  ('Privilege Level: Full','Application: Administers System'),
  ('Privilege Level: Full','Application: Configures Appointment Scheduling'),
  ('Privilege Level: Full','Application: Configures Forms'),
  ('Privilege Level: Full','Application: Configures Metadata'),
  ('Privilege Level: Full','Application: Edits Existing Encounters'),
  ('Privilege Level: Full','Application: Enters ADT Events'),
  ('Privilege Level: Full','Application: Enters Vitals'),
  ('Privilege Level: Full','Application: Has Super User Privileges'),
  ('System Developer','Application: Has Super User Privileges'),
  ('Privilege Level: Full','Application: Manages Atlas'),
  ('Privilege Level: Full','Application: Manages Provider Schedules'),
  ('Privilege Level: Full','Application: Records Allergies'),
  ('Privilege Level: Full','Application: Registers Patients'),
  ('Privilege Level: Full','Application: Requests Appointments'),
  ('Application: Schedules Appointments','Application: Schedules And Overbooks Appointments'),
  ('Privilege Level: Full','Application: Schedules And Overbooks Appointments'),
  ('Application: Sees Appointment Schedule','Application: Schedules Appointments'),
  ('Privilege Level: Full','Application: Schedules Appointments'),
  ('Privilege Level: Full','Application: Sees Appointment Schedule'),
  ('Privilege Level: Full','Application: Uses Capture Vitals App'),
  ('Privilege Level: Full','Application: Uses Patient Summary'),
  ('Privilege Level: Full','Application: Writes Clinical Notes'),
  ('Provider','Careandsupport'),
  ('Application: Registers Patients','cdc_user_role'),
  ('Clinician','cdc_user_role'),
  ('Lab','cdc_user_role'),
  ('Organizational: Registration Clerk','cdc_user_role'),
  ('Application: Enters Vitals','Clinician'),
  ('Application: Records Allergies','Clinician'),
  ('Application: Schedules And Overbooks Appointments','Clinician'),
  ('Application: Sees Appointment Schedule','Clinician'),
  ('Application: Uses Capture Vitals App','Clinician'),
  ('Application: Uses Patient Summary','Clinician'),
  ('Application: Writes Clinical Notes','Clinician'),
  ('Organizational: Doctor','Clinician'),
  ('Privilege Level: Full','Clinician'),
  ('Provider','Clinician'),
  ('Provider','Nurse'),
  ('Privilege Level: Full','Nurse'),
  ('Organizational: Nurse','Nurse'),
  ('Application: Enters Vitals','Nurse'),  
  ('Application: Records Allergies','Nurse'),
  ('Application: Schedules And Overbooks Appointments','Nurse'),
  ('Application: Sees Appointment Schedule','Nurse'),
  ('Application: Uses Capture Vitals App','Nurse'),
  ('Application: Uses Patient Summary','Nurse'),
  ('Application: Writes Clinical Notes','Nurse'),  
  ('Application: Configures Appointment Scheduling','Dataclerk'),
  ('Application: Edits Existing Encounters','Dataclerk'),
  ('Application: Registers Patients','Dataclerk'),
  ('Application: Requests Appointments','Dataclerk'),
  ('Application: Schedules And Overbooks Appointments','Dataclerk'),
  ('Application: Schedules Appointments','Dataclerk'),
  ('Application: Sees Appointment Schedule','Dataclerk'),
  ('Application: Uses Patient Summary','Dataclerk'),
  ('Organizational: Registration Clerk','HTS'),
  ('Privilege Level: Full','HTS'),
  ('Provider','HTS'),
  ('Application: Enters ADT Events','Lab'),
  ('Privilege Level: Full','Lab'),
  ('Provider','Lab'),
  ('Privilege Level: Full','MandE'),
  ('MandE','Application: Schedules Appointments'),  
  ('Provider','MandE'),
  ('Application: Enters ADT Events','Organizational: Doctor'),
  ('Application: Records Allergies','Organizational: Doctor'),
  ('Application: Requests Appointments','Organizational: Doctor'),
  ('Application: Sees Appointment Schedule','Organizational: Doctor'),
  ('Application: Uses Patient Summary','Organizational: Doctor'),
  ('Application: Writes Clinical Notes','Organizational: Doctor'),
  ('Application: Configures Appointment Scheduling','Organizational: Hospital Administrator'),
  ('Application: Manages Provider Schedules','Organizational: Hospital Administrator'),
  ('Application: Requests Appointments','Organizational: Hospital Administrator'),
  ('Application: Schedules And Overbooks Appointments','Organizational: Hospital Administrator'),
  ('Application: Enters ADT Events','Organizational: Nurse'),
  ('Application: Enters Vitals','Organizational: Nurse'),
  ('Application: Records Allergies','Organizational: Nurse'),
  ('Application: Requests Appointments','Organizational: Nurse'),
  ('Application: Sees Appointment Schedule','Organizational: Nurse'),
  ('Application: Uses Capture Vitals App','Organizational: Nurse'),
  ('Application: Uses Patient Summary','Organizational: Nurse'),
  ('Application: Registers Patients','Organizational: Registration Clerk'),
  ('Application: Schedules Appointments','Organizational: Registration Clerk'),
  ('Application: Sees Appointment Schedule','Organizational: Registration Clerk'),
  ('Application: Administers System','Organizational: System Administrator'),
  ('Application: Configures Appointment Scheduling','Organizational: System Administrator'),
  ('Application: Configures Forms','Organizational: System Administrator'),
  ('Application: Configures Metadata','Organizational: System Administrator'),
  ('Application: Manages Atlas','Organizational: System Administrator'),
  ('Application: Manages Provider Schedules','Organizational: System Administrator'),
  ('Privilege Level: Full','Pharmacist'),
   ('Pharmacist','Application: Schedules Appointments'),  
  ('Provider','Pharmacist')/0xd